### ISSUE TITLE
jcache support

### ISSUE THREAD

**Issue by zemiak** [pires/hazelcast-kubernetes#13]
Hello,

how to provide a JCache support? I am copying cache-api.jar to /, setting ENV CLASSPATH / and still getting: com.hazelcast.core.HazelcastException: Service with name 'hz:impl:cacheService' not found!

Thanks for any help!
Miro

**Comment by pires** [comment]
You're copying the JAR to the `/` of where? The node? The container? 🤔

**Comment by zemiak** [comment]
Yes, the container. Does not matter now. I have icluded the jcache support into the bootstrapper itself, that helped:
https://github.com/zemiak/hazelcast-kubernetes-bootstrapper/commit/627c7ae69ee4f5d0f6e6031b1801d4a4bfbf2a30
