### ISSUE TITLE
Push Hazelcast-Kubernetes 3.9 to Quay.io

### ISSUE THREAD

**Issue by oscerd** [pires/hazelcast-kubernetes#18]
@pires can you please push a new image with 3.9 Hazelcast to Quay.io? Thanks.

**Comment by pires** [comment]
On it!

**Comment by pires** [comment]
Fixed in https://github.com/pires/hazelcast-kubernetes/commit/2c7039ddfdbaa5936eb2f35639149055fbe4332c.

**Comment by oscerd** [comment]
Thanks

**Comment by oscerd** [comment]
For other users: just need to wait for https://quay.io/repository/pires/hazelcast-kubernetes?tag=latest&tab=tags

**Comment by pires** [comment]
I screwed up. Fixing.

**Comment by pires** [comment]
Fixed :)

**Comment by oscerd** [comment]
Thanks :-)
