### ISSUE TITLE
kubernetes 1.0.3 CentOS7, Request to Kubernetes API failed

### ISSUE THREAD

**Issue by gaga-github** [pires/hazelcast-kubernetes#8]
I am seeing the same error you mentioned here: [#9075](https://github.com/kubernetes/kubernetes/issues/9075#issuecomment-107893529)

java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token

I installed skydns and tested it following [this guide](http://jamiehannaford.com/setting-up-dns-discovery-in-kubernetes/)
When the apiserver starts up: Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)

Is there a way to further debug the error or do I need to setup my own certs to use? If so, how do it do it correctly?

**Comment by pires** [comment]
How are you installing Kubernetes?

This should tell you [how I configured self-signed certificates for `controller-manager`](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L168).

**Comment by gaga-github** [comment]
[This is what I followed](http://severalnines.com/blog/installing-kubernetes-cluster-minions-centos7-manage-pods-services)

**Comment by gaga-github** [comment]
I figured out my problem, the --admission_control= was missing ServiceAccount from the example install I did.
